package integration.common.response

class PlayerCsgoStatsResponse {

    static def simple(String playerId = "playerId-1") {
        """
            {
              "player_id": "$playerId",
              "game_id": "csgo",
              "lifetime": {
                "Average Headshots %": "35",
                "Average K/D Ratio": "1.59",
                "Current Win Streak": "0",
                "K/D Ratio": "4410.35",
                "Longest Win Streak": "36",
                "Matches": "2776",
                "Recent Results": [
                  "0",
                  "1",
                  "1",
                  "1",
                  "0"
                ],
                "Total Headshots %": "96703",
                "Win Rate %": "63",
                "Wins": "1758"
              },
              "segments": [
                {
                  "img_regular": "https://cdn.faceit.com/static/stats_assets/csgo/maps/200x125/csgo-votable-maps-de_cache-200x125.jpg",
                  "img_small": "https://cdn.faceit.com/static/stats_assets/csgo/maps/110x55/csgo-votable-maps-de_cache-110x55.jpg",
                  "label": "de_cache",
                  "mode": "5v5",
                  "stats": {
                    "Assists": "1202",
                    "Average Assists": "3.15",
                    "Average Deaths": "17.72",
                    "Average Headshots %": "37",
                    "Average K/D Ratio": "1.52",
                    "Average K/R Ratio": "0.93",
                    "Average Kills": "23.99",
                    "Average MVPs": "3.83",
                    "Average Penta Kills": "0.06",
                    "Average Quadro Kills": "0.41",
                    "Average Triple Kills": "1.69",
                    "Deaths": "6753",
                    "Headshots": "3333",
                    "Headshots per Match": "8.75",
                    "K/D Ratio": "578.19",
                    "K/R Ratio": "354.77",
                    "Kills": "9139",
                    "MVPs": "1461",
                    "Matches": "381",
                    "Penta Kills": "22",
                    "Quadro Kills": "158",
                    "Rounds": "9932",
                    "Total Headshots %": "14008",
                    "Triple Kills": "642",
                    "Win Rate %": "57",
                    "Wins": "219"
                  },
                  "type": "Map"
                },
                {
                  "img_regular": "https://cdn.faceit.com/static/stats_assets/csgo/maps/200x125/csgo-votable-maps-de_overpass-200x125.jpg",
                  "img_small": "https://cdn.faceit.com/static/stats_assets/csgo/maps/110x55/csgo-votable-maps-de_overpass-110x55.jpg",
                  "label": "de_overpass",
                  "mode": "5v5",
                  "stats": {
                    "Assists": "1504",
                    "Average Assists": "3.25",
                    "Average Deaths": "16.75",
                    "Average Headshots %": "34",
                    "Average K/D Ratio": "1.74",
                    "Average K/R Ratio": "1.02",
                    "Average Kills": "25.92",
                    "Average MVPs": "4.34",
                    "Average Penta Kills": "0.08",
                    "Average Quadro Kills": "0.53",
                    "Average Triple Kills": "1.9",
                    "Deaths": "7756",
                    "Headshots": "4004",
                    "Headshots per Match": "8.65",
                    "K/D Ratio": "805.38",
                    "K/R Ratio": "471.65",
                    "Kills": "12001",
                    "MVPs": "2008",
                    "Matches": "463",
                    "Penta Kills": "35",
                    "Quadro Kills": "244",
                    "Rounds": "11860",
                    "Total Headshots %": "15737",
                    "Triple Kills": "879",
                    "Win Rate %": "71",
                    "Wins": "327"
                  },
                  "type": "Map"
                },
                {
                  "img_regular": "https://cdn.faceit.com/static/stats_assets/csgo/maps/200x125/csgo-votable-maps-de_dust2-200x125.jpg",
                  "img_small": "https://cdn.faceit.com/static/stats_assets/csgo/maps/110x55/csgo-votable-maps-de_dust2-110x55.jpg",
                  "label": "de_dust2",
                  "mode": "5v5",
                  "stats": {
                    "Assists": "765",
                    "Average Assists": "3.21",
                    "Average Deaths": "17.46",
                    "Average Headshots %": "35",
                    "Average K/D Ratio": "1.58",
                    "Average K/R Ratio": "0.97",
                    "Average Kills": "25.18",
                    "Average MVPs": "3.94",
                    "Average Penta Kills": "0.07",
                    "Average Quadro Kills": "0.46",
                    "Average Triple Kills": "1.88",
                    "Deaths": "4155",
                    "Headshots": "2063",
                    "Headshots per Match": "8.67",
                    "K/D Ratio": "375.2",
                    "K/R Ratio": "231.24",
                    "Kills": "5992",
                    "MVPs": "937",
                    "Matches": "238",
                    "Penta Kills": "17",
                    "Quadro Kills": "109",
                    "Rounds": "6223",
                    "Total Headshots %": "8221",
                    "Triple Kills": "447",
                    "Win Rate %": "63",
                    "Wins": "151"
                  },
                  "type": "Map"
                },
                {
                  "img_regular": "https://cdn.faceit.com/static/stats_assets/csgo/maps/200x125/csgo-votable-maps-de_mirage-200x125.jpg",
                  "img_small": "https://cdn.faceit.com/static/stats_assets/csgo/maps/110x55/csgo-votable-maps-de_mirage-110x55.jpg",
                  "label": "de_mirage",
                  "mode": "5v5",
                  "stats": {
                    "Assists": "2377",
                    "Average Assists": "3.02",
                    "Average Deaths": "17.15",
                    "Average Headshots %": "35",
                    "Average K/D Ratio": "1.6",
                    "Average K/R Ratio": "0.94",
                    "Average Kills": "24.29",
                    "Average MVPs": "3.85",
                    "Average Penta Kills": "0.04",
                    "Average Quadro Kills": "0.38",
                    "Average Triple Kills": "1.74",
                    "Deaths": "13512",
                    "Headshots": "6529",
                    "Headshots per Match": "8.29",
                    "K/D Ratio": "1262.14",
                    "K/R Ratio": "741.2",
                    "Kills": "19142",
                    "MVPs": "3031",
                    "Matches": "788",
                    "Penta Kills": "35",
                    "Quadro Kills": "296",
                    "Rounds": "20537",
                    "Total Headshots %": "27539",
                    "Triple Kills": "1375",
                    "Win Rate %": "64",
                    "Wins": "506"
                  },
                  "type": "Map"
                },
                {
                  "img_regular": "https://cdn.faceit.com/static/stats_assets/csgo/maps/200x125/csgo-votable-maps-de_cbbl-200x125.jpg",
                  "img_small": "https://cdn.faceit.com/static/stats_assets/csgo/maps/110x55/csgo-votable-maps-de_cbbl-110x55.jpg",
                  "label": "de_cbble",
                  "mode": "5v5",
                  "stats": {
                    "Assists": "481",
                    "Average Assists": "3.34",
                    "Average Deaths": "17.94",
                    "Average Headshots %": "36",
                    "Average K/D Ratio": "1.56",
                    "Average K/R Ratio": "0.95",
                    "Average Kills": "25.08",
                    "Average MVPs": "4.06",
                    "Average Penta Kills": "0.06",
                    "Average Quadro Kills": "0.53",
                    "Average Triple Kills": "1.84",
                    "Deaths": "2584",
                    "Headshots": "1297",
                    "Headshots per Match": "9.01",
                    "K/D Ratio": "224.17",
                    "K/R Ratio": "136.62",
                    "Kills": "3612",
                    "MVPs": "584",
                    "Matches": "144",
                    "Penta Kills": "8",
                    "Quadro Kills": "77",
                    "Rounds": "3804",
                    "Total Headshots %": "5123",
                    "Triple Kills": "265",
                    "Win Rate %": "58",
                    "Wins": "83"
                  },
                  "type": "Map"
                },
                {
                  "img_regular": "https://cdn.faceit.com/static/stats_assets/csgo/maps/200x125/csgo-votable-maps-de_train-200x125.jpg",
                  "img_small": "https://cdn.faceit.com/static/stats_assets/csgo/maps/110x55/csgo-votable-maps-de_train-110x55.jpg",
                  "label": "de_train",
                  "mode": "5v5",
                  "stats": {
                    "Assists": "1244",
                    "Average Assists": "2.8",
                    "Average Deaths": "17.28",
                    "Average Headshots %": "32",
                    "Average K/D Ratio": "1.56",
                    "Average K/R Ratio": "0.92",
                    "Average Kills": "24.52",
                    "Average MVPs": "3.79",
                    "Average Penta Kills": "0.03",
                    "Average Quadro Kills": "0.42",
                    "Average Triple Kills": "1.67",
                    "Deaths": "7674",
                    "Headshots": "3419",
                    "Headshots per Match": "7.7",
                    "K/D Ratio": "693",
                    "K/R Ratio": "410.14",
                    "Kills": "10885",
                    "MVPs": "1684",
                    "Matches": "444",
                    "Penta Kills": "14",
                    "Quadro Kills": "187",
                    "Rounds": "11845",
                    "Total Headshots %": "14285",
                    "Triple Kills": "743",
                    "Win Rate %": "63",
                    "Wins": "279"
                  },
                  "type": "Map"
                },
                {
                  "img_regular": "https://cdn.faceit.com/static/stats_assets/csgo/maps/200x125/csgo-votable-maps-de_inferno-200x125.jpg",
                  "img_small": "https://cdn.faceit.com/static/stats_assets/csgo/maps/110x55/csgo-votable-maps-de_inferno-110x55.jpg",
                  "label": "de_inferno",
                  "mode": "5v5",
                  "stats": {
                    "Assists": "619",
                    "Average Assists": "3.24",
                    "Average Deaths": "18.46",
                    "Average Headshots %": "36",
                    "Average K/D Ratio": "1.44",
                    "Average K/R Ratio": "0.9",
                    "Average Kills": "24.24",
                    "Average MVPs": "3.85",
                    "Average Penta Kills": "0.04",
                    "Average Quadro Kills": "0.47",
                    "Average Triple Kills": "1.81",
                    "Deaths": "3526",
                    "Headshots": "1618",
                    "Headshots per Match": "8.47",
                    "K/D Ratio": "274.44",
                    "K/R Ratio": "172.01",
                    "Kills": "4630",
                    "MVPs": "736",
                    "Matches": "191",
                    "Penta Kills": "8",
                    "Quadro Kills": "89",
                    "Rounds": "5197",
                    "Total Headshots %": "6813",
                    "Triple Kills": "346",
                    "Win Rate %": "59",
                    "Wins": "113"
                  },
                  "type": "Map"
                }
              ]
            }
        """
    }
}
