{
 "title": "Tuscan App",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Endpoints p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(httpServerRequests.exception.None.method.GET.outcome.SUCCESS.status.200.uri._faceit_matches.p99, 'faceit-matches')"
    },
    {
     "target": "alias(httpServerRequests.exception.None.method.GET.outcome.SUCCESS.status.200.uri._faceit_matches_simple.p99, 'faceit-matches-simple')"
    },
    {
     "target": "alias(httpServerRequests.exception.None.method.GET.outcome.SUCCESS.status.200.uri._tuscan-api_plugin_players_details_csgo.p99, 'plugin')"
    },
    {
     "target": "alias(httpServerRequests.exception.None.method.GET.outcome.SUCCESS.status.200.uri._faceit_search_players.p99, 'search')"
    },
    {
     "target": "alias(httpServerRequests.exception.None.method.GET.outcome.SUCCESS.status.200.uri._faceit_player_position.p99, 'player-position')"
    },
    {
     "target": "alias(httpServerRequests.exception.None.method.GET.outcome.SUCCESS.status.200.uri._faceit_player-history__playerId_.p99, 'player-history')"
    },
    {
     "target": "alias(httpServerRequests.exception.None.method.GET.outcome.SUCCESS.status.200.uri._faceit_players_details_csgo__playerId_.p99, 'player-csgo-details')"
    },
    {
     "target": "alias(httpServerRequests.exception.None.method.GET.outcome.SUCCESS.status.200.uri._tuscan-api_latest-profiles.p99, 'latest-profiles')"
    },
    {
     "target": "alias(httpServerRequests.exception.None.method.GET.outcome.SUCCESS.status.200.uri._faceit_players_details.p99, 'player-details')"
    },
    {
     "target": "alias(httpServerRequests.exception.None.method.POST.outcome.SUCCESS.status.201.uri._tuscan-api_demo-parser.p99, 'demo-parser')"
    }
   ]
  },
  {
   "title": "Faceit API p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(reactorFlowDuration.exception.flow.csgoStats.status.completed.type.Mono.p99, 'get-csgo-stats')"
    },
    {
     "target": "alias(reactorFlowDuration.exception.flow.matchDetails.status.completed.type.Mono.p99, 'match-details')"
    },
    {
     "target": "alias(reactorFlowDuration.exception.flow.matches.status.completed.type.Mono.p99, 'matches')"
    },
    {
     "target": "alias(reactorFlowDuration.exception.flow.playerDetails.status.completed.type.Mono.p99, 'player-details')"
    },
    {
     "target": "alias(reactorFlowDuration.exception.flow.playerHistory.status.completed.type.Mono.p99, 'player-history')"
    },
    {
     "target": "alias(reactorFlowDuration.exception.flow.positionInCountry.status.completed.type.Mono.p99, 'position-country')"
    },
    {
     "target": "alias(reactorFlowDuration.exception.flow.positionInRegion.status.completed.type.Mono.p99, 'position-region')"
    },
    {
     "target": "alias(reactorFlowDuration.exception.flow.searchPlayer.status.completed.type.Mono.p99, 'search')"
    },
    {
     "target": "alias(reactorFlowDuration.exception.flow.matchDemo.status.completed.type.Mono.p99, 'demo')"
    }
   ]
  },
  {
   "title": "Cumulated Traffic (m1_rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(httpServerRequests.*.None.method.*.*.*.status.2**.uri.*.m1_rate), '2xx')"
    },
    {
     "target": "alias(sumSeries(httpServerRequests.*.None.method.*.*.*.status.4**.uri.*.m1_rate), '4xx')"
    },
    {
     "target": "alias(sumSeries(httpServerRequests.*.None.method.*.*.*.status.5**.uri.*.m1_rate), '5xx')"
    }
   ]
  },
  {
   "title": "Faceit API Calls",
   "type": "gauge",
   "description": "Calls to API by key",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "target": "sumSeries(reactorSubscribed.*.*.type.Mono.count)"
    }
   ]
  },
  {
   "title": "JVM memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "jvmMemoryUsed.area.heap.id.Eden_Space"
    },
    {
     "target": "jvmMemoryUsed.area.heap.id.Survivor_Space"
    },
    {
     "target": "jvmMemoryUsed.area.heap.id.Tenured_Gen"
    },
    {
     "target": "jvmMemoryUsed.area.nonheap.id.Code_Cache"
    },
    {
     "target": "jvmMemoryUsed.area.nonheap.id.Metaspace"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "systemCpuUsage" }
   ]
  },
  {
   "title": "Threads live",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(jvmThreadsLive, 'threads-live')"
    },
    {
     "target": "alias(jvmThreadsStates.state.blocked, 'blocked')"
    },
    {
     "target": "alias(jvmThreadsStates.state.new, 'new-threads')"
    },
    {
     "target": "alias(jvmThreadsStates.state.runnable, 'runnable')"
    },
    {
     "target": "alias(jvmThreadsStates.state.terminated, 'terminated')"
    },
    {
     "target": "alias(jvmThreadsStates.state.timed-waiting, 'timed-waiting')"
    },
    {
     "target": "alias(jvmThreadsStates.state.waiting, 'waiting')"
    }
   ]
  },
  {
   "title": "Garbage Collector p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "jvmGcPause.action.end_of_major_GC.cause.Metadata_GC_Threshold.p99"
    },
    {
     "target": "jvmGcPause.action.end_of_minor_GC.cause.*.p99"
    }
   ]
  },
  {
   "title": "Logback levels",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(logbackEvents.level.error.m1_rate, 'error')"
    },
    {
     "target": "alias(logbackEvents.level.info.m1_rate, 'info')"
    },
    {
     "target": "alias(logbackEvents.level.warn.m1_rate, 'warn')"
    }
   ]
  }
 ]
}